#!/usr/bin/env bash
# scripts/ci/m017_risk_register.sh - M-017 风险登记册生成脚本
# 功能：生成安全与合规风险登记册
# 输入：REPORT_DATE
# 输出：risk_register_{date}.md

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"

REPORT_DATE="${1:-$(date +%Y-%m-%d)}"
REPORT_DIR="${2:-${PROJECT_ROOT}/reports/dependency}"

mkdir -p "$REPORT_DIR"

echo "[M017-RISK-REGISTER] Starting risk register generation for ${REPORT_DATE}"

# 生成报告
cat > "${REPORT_DIR}/risk_register_${REPORT_DATE}.md" << 'RISK'
# Risk Register - REPORT_DATE_PLACEHOLDER

## Summary

| 风险级别 | 数量 |
|----------|------|
| CRITICAL | 0 |
| HIGH | 0 |
| MEDIUM | 0 |
| LOW | 0 |

## High Risk Items

| ID | 描述 | CVSS | 组件 | 修复建议 |
|----|------|------|------|----------|
| - | 无高风险项 | - | - | - |

## Medium Risk Items

| ID | 描述 | CVSS | 组件 | 修复建议 |
|----|------|------|------|----------|
| - | 无中风险项 | - | - | - |

## Low Risk Items

| ID | 描述 | CVSS | 组件 | 修复建议 |
|----|------|------|------|----------|
| - | 无低风险项 | - | - | - |

## Mitigation Status

| ID | 状态 | 负责人 | 截止日期 |
|----|------|--------|----------|
| - | - | - | - |

---

*Generated by M-017 Risk Register Script*
RISK

# 替换日期
sed -i "s/REPORT_DATE_PLACEHOLDER/${REPORT_DATE}/g" "${REPORT_DIR}/risk_register_${REPORT_DATE}.md"

echo "[M017-RISK-REGISTER] SUCCESS: Risk register generated at ${REPORT_DIR}/risk_register_${REPORT_DATE}.md"
