-- Platform core schema baseline (PostgreSQL 15)
-- Purpose: provide non-supply core domain tables required by PRD P0/P1.
-- Boundary:
--   - This file is the platform-side fresh setup baseline under repository root /sql/postgresql.
--   - audit_events in this file belongs to the platform/core domain timeline.
--   - It is not the same baseline as supply-api/sql/postgresql/partition_strategy_v1.sql.
--   - Do not stack both audit_events definitions into one fresh database without an explicit schema/database split.
-- Updated: 2026-03-27

BEGIN;

CREATE TABLE IF NOT EXISTS core_tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(64) NOT NULL UNIQUE,
    tenant_name VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'suspended', 'disabled')),
    plan_code VARCHAR(32) NOT NULL DEFAULT 'free',
    billing_currency CHAR(3) NOT NULL DEFAULT 'USD',
    timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_core_tenants_status ON core_tenants (status);
CREATE INDEX IF NOT EXISTS idx_core_tenants_plan_code ON core_tenants (plan_code);

CREATE TABLE IF NOT EXISTS core_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES core_tenants(id),
    project_code VARCHAR(64) NOT NULL,
    project_name VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'archived')),
    budget_minor BIGINT,
    budget_currency CHAR(3) NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    UNIQUE (tenant_id, project_code)
);

CREATE INDEX IF NOT EXISTS idx_core_projects_tenant_status ON core_projects (tenant_id, status);

CREATE TABLE IF NOT EXISTS iam_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES core_tenants(id),
    email VARCHAR(256) NOT NULL,
    display_name VARCHAR(128),
    role_code VARCHAR(32) NOT NULL DEFAULT 'developer',
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'locked', 'disabled')),
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, email)
);

CREATE INDEX IF NOT EXISTS idx_iam_users_tenant_role ON iam_users (tenant_id, role_code);
CREATE INDEX IF NOT EXISTS idx_iam_users_tenant_status ON iam_users (tenant_id, status);

CREATE TABLE IF NOT EXISTS auth_platform_api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES core_tenants(id),
    project_id BIGINT REFERENCES core_projects(id),
    user_id BIGINT REFERENCES iam_users(id),
    key_prefix VARCHAR(16) NOT NULL,
    key_hash CHAR(64) NOT NULL,
    hash_algo VARCHAR(32) NOT NULL DEFAULT 'HMAC-SHA256',
    scope_code VARCHAR(64) NOT NULL DEFAULT 'gateway.invoke',
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'revoked', 'expired')),
    expires_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    revoked_by BIGINT,
    revoked_reason TEXT,
    UNIQUE (tenant_id, key_prefix)
);

CREATE INDEX IF NOT EXISTS idx_auth_platform_api_keys_tenant_status ON auth_platform_api_keys (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_auth_platform_api_keys_project_status ON auth_platform_api_keys (project_id, status);
CREATE INDEX IF NOT EXISTS idx_auth_platform_api_keys_last_used_at ON auth_platform_api_keys (last_used_at);

CREATE TABLE IF NOT EXISTS billing_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES core_tenants(id),
    project_id BIGINT REFERENCES core_projects(id),
    account_type VARCHAR(20) NOT NULL DEFAULT 'prepaid'
        CHECK (account_type IN ('prepaid', 'postpaid')),
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'frozen', 'closed')),
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    available_minor BIGINT NOT NULL DEFAULT 0,
    frozen_minor BIGINT NOT NULL DEFAULT 0,
    credit_limit_minor BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, project_id, account_type)
);

CREATE INDEX IF NOT EXISTS idx_billing_accounts_tenant_status ON billing_accounts (tenant_id, status);

CREATE TABLE IF NOT EXISTS billing_ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_account_id BIGINT NOT NULL REFERENCES billing_accounts(id),
    tenant_id BIGINT NOT NULL REFERENCES core_tenants(id),
    project_id BIGINT REFERENCES core_projects(id),
    user_id BIGINT REFERENCES iam_users(id),
    request_id VARCHAR(64) NOT NULL,
    trace_id VARCHAR(64),
    entry_type VARCHAR(32) NOT NULL,
    direction VARCHAR(2) NOT NULL CHECK (direction IN ('dr', 'cr')),
    amount_minor BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    amount_unit VARCHAR(16) NOT NULL DEFAULT 'minor',
    balance_after_minor BIGINT,
    ref_type VARCHAR(32),
    ref_id BIGINT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idempotency_key VARCHAR(128),
    UNIQUE (tenant_id, request_id, entry_type)
);

CREATE INDEX IF NOT EXISTS idx_billing_ledger_entries_account_time ON billing_ledger_entries (billing_account_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_billing_ledger_entries_tenant_time ON billing_ledger_entries (tenant_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_billing_ledger_entries_trace_id ON billing_ledger_entries (trace_id);

CREATE TABLE IF NOT EXISTS routing_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES core_tenants(id),
    project_id BIGINT REFERENCES core_projects(id),
    policy_name VARCHAR(128) NOT NULL,
    model_pattern VARCHAR(128) NOT NULL,
    strategy_code VARCHAR(32) NOT NULL,
    provider_group VARCHAR(64),
    priority INT NOT NULL DEFAULT 100,
    weight INT,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled')),
    version BIGINT NOT NULL DEFAULT 1,
    effective_from TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    effective_to TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_routing_policies_tenant_project_status
    ON routing_policies (tenant_id, project_id, status);
CREATE INDEX IF NOT EXISTS idx_routing_policies_model_pattern ON routing_policies (model_pattern);

CREATE TABLE IF NOT EXISTS security_kms_key_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_alias VARCHAR(128) NOT NULL UNIQUE,
    provider VARCHAR(32) NOT NULL,
    key_spec VARCHAR(64) NOT NULL,
    cipher_algo VARCHAR(32) NOT NULL,
    key_version INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'rotating', 'retired')),
    rotated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_security_kms_key_registry_status
    ON security_kms_key_registry (status);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES core_tenants(id),
    project_id BIGINT REFERENCES core_projects(id),
    actor_user_id BIGINT REFERENCES iam_users(id),
    actor_type VARCHAR(32) NOT NULL,
    domain_code VARCHAR(32) NOT NULL,
    object_type VARCHAR(64) NOT NULL,
    object_id VARCHAR(128),
    action_code VARCHAR(64) NOT NULL,
    result_code VARCHAR(32) NOT NULL,
    severity VARCHAR(16) NOT NULL DEFAULT 'info'
        CHECK (severity IN ('info', 'warn', 'error', 'critical')),
    request_id VARCHAR(64),
    trace_id VARCHAR(64),
    idempotency_key VARCHAR(128),
    client_ip INET,
    user_agent VARCHAR(256),
    before_data JSONB,
    after_data JSONB,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_events_tenant_domain_time
    ON audit_events (tenant_id, domain_code, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_request_id ON audit_events (request_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_trace_id ON audit_events (trace_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_result_code ON audit_events (result_code);

COMMIT;
